CRITICAL - 2020-11-02 09:22:33 --> Unable to connect to the database.
#0 C:\Users\Gebruiker\Desktop\SCHOOL\Master\RenD\Code\a20ux1\system\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->initialize()
#1 C:\Users\Gebruiker\Desktop\SCHOOL\Master\RenD\Code\a20ux1\app\Models\Database_model.php(16): CodeIgniter\Database\BaseConnection->query('SELECT DISTINCT...')
#2 C:\Users\Gebruiker\Desktop\SCHOOL\Master\RenD\Code\a20ux1\app\Controllers\Newcontroller.php(26): Database_model->get_data()
#3 C:\Users\Gebruiker\Desktop\SCHOOL\Master\RenD\Code\a20ux1\system\CodeIgniter.php(918): App\Controllers\Newcontroller->about()
#4 C:\Users\Gebruiker\Desktop\SCHOOL\Master\RenD\Code\a20ux1\system\CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Newcontroller))
#5 C:\Users\Gebruiker\Desktop\SCHOOL\Master\RenD\Code\a20ux1\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\Users\Gebruiker\Desktop\SCHOOL\Master\RenD\Code\a20ux1\public\index.php(45): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2020-11-02 09:22:33 --> Uncaught ErrorException: print_r(): Property access is not allowed yet in C:\Users\Gebruiker\Desktop\SCHOOL\Master\RenD\Code\a20ux1\app\Views\errors\html\error_exception.php:100
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'print_r(): Prop...', 'C:\\Users\\Gebrui...', 100, Array)
#1 C:\Users\Gebruiker\Desktop\SCHOOL\Master\RenD\Code\a20ux1\app\Views\errors\html\error_exception.php(100): print_r(Object(App\Controllers\Newcontroller), true)
#2 C:\Users\Gebruiker\Desktop\SCHOOL\Master\RenD\Code\a20ux1\system\Debug\Exceptions.php(308): include('C:\\Users\\Gebrui...')
#3 C:\Users\Gebruiker\Desktop\SCHOOL\Master\RenD\Code\a20ux1\system\Debug\Exceptions.php(174): CodeIgniter\Debug\Exceptions->render(Object(CodeIgniter\Database\Exceptions\DatabaseException), 500)
#4 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Database\Exceptions\DatabaseException))
#5 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2020-11-02 09:23:01 --> Unable to connect to the database.
#0 C:\Users\Gebruiker\Desktop\SCHOOL\Master\RenD\Code\a20ux1\system\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->initialize()
#1 C:\Users\Gebruiker\Desktop\SCHOOL\Master\RenD\Code\a20ux1\app\Models\Database_model.php(16): CodeIgniter\Database\BaseConnection->query('SELECT DISTINCT...')
#2 C:\Users\Gebruiker\Desktop\SCHOOL\Master\RenD\Code\a20ux1\app\Controllers\Newcontroller.php(26): Database_model->get_data()
#3 C:\Users\Gebruiker\Desktop\SCHOOL\Master\RenD\Code\a20ux1\system\CodeIgniter.php(918): App\Controllers\Newcontroller->about()
#4 C:\Users\Gebruiker\Desktop\SCHOOL\Master\RenD\Code\a20ux1\system\CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Newcontroller))
#5 C:\Users\Gebruiker\Desktop\SCHOOL\Master\RenD\Code\a20ux1\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\Users\Gebruiker\Desktop\SCHOOL\Master\RenD\Code\a20ux1\public\index.php(45): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2020-11-02 09:23:01 --> Uncaught ErrorException: print_r(): Property access is not allowed yet in C:\Users\Gebruiker\Desktop\SCHOOL\Master\RenD\Code\a20ux1\app\Views\errors\html\error_exception.php:100
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'print_r(): Prop...', 'C:\\Users\\Gebrui...', 100, Array)
#1 C:\Users\Gebruiker\Desktop\SCHOOL\Master\RenD\Code\a20ux1\app\Views\errors\html\error_exception.php(100): print_r(Object(App\Controllers\Newcontroller), true)
#2 C:\Users\Gebruiker\Desktop\SCHOOL\Master\RenD\Code\a20ux1\system\Debug\Exceptions.php(308): include('C:\\Users\\Gebrui...')
#3 C:\Users\Gebruiker\Desktop\SCHOOL\Master\RenD\Code\a20ux1\system\Debug\Exceptions.php(174): CodeIgniter\Debug\Exceptions->render(Object(CodeIgniter\Database\Exceptions\DatabaseException), 500)
#4 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Database\Exceptions\DatabaseException))
#5 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
